# Generated by Django 2.0.7 on 2019-05-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
